### PR TITLE
Adds an availableFields decoder

### LINKED ISSUE #28: Decoder API to get available fields
```elm

headers : Decoder (List String)
```

or some such.

The main use case I have is that the format of CSV my application accepts is dynamic based on the state of the application.

(i.e there are columns called `1_fx`, `1_fy`, `2_fx`, `2_fy`, `3_fx`, `3_fy`, ...)

Hence I would like to have an easy way to validate that there are no extra columns matching the template, since that would indicate that the user provided a CSV that didn't match the state of the application.

### PR DESCRIPTION
**Pull request by gampleman**
Closes #28.

### CODE REVIEW

**Review by BrianHicks — CHANGES_REQUESTED** [review]
the library code itself looks good! Would you please add some tests showing expected behavior? Also, I think this should probably fail with `NoFieldNames`, shouldn't it? It's not that there are 0 fields present in that case, it's that there is not even a row for them.

**Comment by gampleman** [comment]
> I think this should probably fail with NoFieldNames, shouldn't it? It's not that there are 0 fields present in that case, it's that there is not even a row for them.

I thought of this, but sort of figured that providing an empty list in that case would be more composable (since this is a decoder that is unlikely to be used "on its own", but rather is a building block to make something more elaborate). It seems that having relatively stable behavior regardless of config would aid that.

(It also makes the implementation simpler, since I don't think it's easy to detect if we are in an empty list situation or if it's just `NoFieldNames`).

Happy to attempt to change this, but might need a bit more invasive changes to achieve, let me know what you think.

**Comment by BrianHicks** [comment]
I've thought on it a couple times over the last few days and I keep coming back to the fact that you shouldn't be able to request field names when you explicitly said there were none. That seems like an error! I would like to prevent this in the type system, but I don't think that we really can. The next best thing to do would probably be to throw an error. I know it's harder to write and maintain, but that's the tradeoff we make as library authors! 😆 

What do you think about trying to make this happen? I can give the refactor a shot before/after merging this, but I'm not likely to have a lot of time to address this in the next couple of weeks so it'd be a further delay if it's something you need right away.

**Comment by gampleman** [comment]
OK, I can give it a shot. Does it make sense to try to merge in some of the other PRs (since if I need to touch some of the other types this could end up in conflict hell?)

**Comment by BrianHicks** [comment]
yeah, maybe. What would you suggest? #34 and #30?

**Comment by BrianHicks** [comment]
I just fixed CI in the main branch; you should be able to merge/rebase to get it green there, then we can get stuff merging.

**Comment by BrianHicks** [comment]
do you want to resurrect this PR? Fine if no.

**Comment by gampleman** [comment]
I'll probably circle back to it when I'm next working on CSVs. I'm not really in the brain space at the moment...

**Comment by BrianHicks** [comment]
Excellent! Thanks so much! I think that’s the last of the PRs, right?

I’m out this week but if we’re good now I’ll cut the next major version sometime the first week or April.

**Comment by gampleman** [comment]
This is merged a bit prematurely, I haven’t done the error reporting bit yet.

I can do another PR to add that tomorrow if you want?

**Comment by BrianHicks** [comment]
whoops! Go ahead.

**Comment by gampleman** [comment]
@BrianHicks done in #37. After that I think that's it for me, so happy for a release to be cut from my side.

**Pull request merged**
