### PR TITLE
Implements optionalField

### LINKED ISSUE #23: Optional columns
In our application there are some required columns the user submit and some are optional.

At the moment I encode this like this:

```elm
optional :Decoder a -> Decoder (Maybe a -> b) -> Decoder b
optional default childDecoder =
    pipeline (Csv.oneOf (Csv.map Just childDecoder) [ Csv.succeed Nothing ])

decoder =
    Csv.into Tuple.pair 
         |> pipeline (Csv.field "requiredColumn" Csv.float)
         |> optional (Csv.field "optionalColumn" Csv.float)

```

This sort of works, but has some subtle behavioural gotchas:

requiredColumn | optionalColumn
-----------------|----------------
1  | 2
2 | four
3 | 6

would successfully decode into:

```elm
[ ( 1, Just 2 ), ( 2, Nothing ), (3, Just 6) ]
```

which is not what I want. In this case I'd like to flag the error to the user, but I'd still like to mark some columns as optional. I can't really see a way to achieve this with the current API. So I'd propose something like 

```elm
optionalField : String -> Decoder a -> Decoder (Maybe a)
```

which would only go to the `Nothing` case iff the column was not present at all in the CSV.

### PR DESCRIPTION
**Pull request by gampleman**
An alternative implementation to #29. Fixes #23.

I think here the implementation is nicer and the semantics of the API are more obvious, but I sort of got the impression in #23 that you preferred the API in #29.

A small further advantage here is that it is a minor version change.

### CODE REVIEW

**Comment by BrianHicks** [comment]
hmm! I think this actually could be quite nice, although then we probably need `optionalColumn` as well. What do you think?

**Comment by gampleman** [comment]
I didn't personally need that one, but could quite easily add it if you think that makes sense... you could always wait until someone complains about it...

**Comment by BrianHicks** [comment]
I'd prefer the API be cohesive instead of making people file issues for things that the API *should* have by implication. I think this might be best, especially since it makes a minor version bump instead of a major one!

**Comment by gampleman** [comment]
OK, done.

**Pull request merged**
